"use client";

import { useState } from "react";
import { FaChevronDown } from "react-icons/fa6";

const faqs = [
  {
    question: "How does Blog GPT generate blog content?",
    answer:
      "Blog GPT uses Gemini AI to create blog posts based on the topic or keywords you provide. The system analyzes your input and generates a well structured draft that you can edit, refine, and publish according to your needs.",
  },
  {
    question: "Is Blog GPT free to use?",
    answer:
      "Yes. Blog GPT offers a free plan that allows you to generate up to five blog posts per month. This helps you explore the platform and understand how it works before choosing a paid plan.",
  },
  {
    question: "How fast does Blog GPT generate a blog post?",
    answer:
      "In most cases, Blog GPT generates a complete blog post in less than thirty seconds. More detailed topics may take slightly longer, but you will usually receive a draft within a minute.",
  },
  {
    question: "Can I edit the content generated by Blog GPT?",
    answer:
      "Yes, all generated content is fully editable. You can change the wording, add new sections, remove parts you do not need, and customize the article before publishing it.",
  },
  {
    question: "What kind of customer support does Blog GPT provide?",
    answer:
      "Blog GPT provides email support for all users, with replies typically within twenty four to forty eight hours. Users on the Pro plan receive faster responses along with access to helpful documentation and video guides.",
  },
];

export default function FaqSection() {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  const toggle = (index: number) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <section className="py-16 px-6 sm:px-16 lg:px-28">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <div className="text-center mb-14">
          <h2 className="text-3xl sm:text-4xl font-bold text-gray-900 dark:text-white">
            Frequently Asked Questions
          </h2>
          <p className="mt-4 text-lg text-gray-600 dark:text-gray-400">
            Everything you need to know about Blog-GPT
          </p>
        </div>

        {/* Accordion */}
        <div className="space-y-4">
          {faqs.map((faq, index) => {
            const isOpen = openIndex === index;

            return (
              <div
                key={index}
                className="rounded-xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-dark-100 overflow-hidden"
              >
                <button
                  onClick={() => toggle(index)}
                  aria-expanded={isOpen}
                  className="w-full flex items-center justify-between px-6 py-5 text-left text-lg font-semibold text-gray-900 dark:text-white"
                >
                  {faq.question}
                  <FaChevronDown
                    className={`transition-transform duration-300 ${
                      isOpen ? "rotate-180" : ""
                    }`}
                  />
                </button>

                {/* Animated content */}
                <div
                  className={`grid transition-all duration-300 ease-in-out ${
                    isOpen
                      ? "grid-rows-[1fr] opacity-100"
                      : "grid-rows-[0fr] opacity-0"
                  }`}
                >
                  <div className="overflow-hidden px-6 pb-5 text-gray-600 dark:text-gray-400">
                    {faq.answer}
                  </div>
                </div>
              </div>
            );
          })}
        </div>

        {/* CTA */}
        <div className="text-center mt-14">
          <p className="text-gray-600 dark:text-gray-400 mb-6">
            Still have questions?
          </p>
          <a
            href="mailto:support@bloggpt.com"
            className="inline-block bg-blue-600 hover:bg-blue-700 text-white font-semibold py-3 px-8 rounded-lg transition"
          >
            Contact Support
          </a>
        </div>
      </div>
    </section>
  );
}
